namespace Axon.Cuda.Common.Interop;

public enum CudaErrorCode : int
{
    Success = 0,
    MissingConfiguration = 52,
    MemoryAllocation = 2,
    InitializationError = 3,
    LaunchFailure = 53,
    LaunchTimeout = 702,
    LaunchOutOfResources = 701,
    InvalidDeviceFunction = 98,
    InvalidConfiguration = 9,
    InvalidDevice = 101,
    InvalidValue = 1,
    InvalidPitchValue = 12,
    InvalidSymbol = 13,
    UnmapBufferObjectFailed = 206,
    InvalidDevicePointer = 17,
    InvalidTexture = 18,
    InvalidTextureBinding = 19,
    InvalidChannelDescriptor = 20,
    InvalidMemcpyDirection = 21,
    InvalidFilterSetting = 26,
    InvalidNormSetting = 27,
    Unknown = 999,
    InvalidResourceHandle = 400,
    InsufficientDriver = 32,
    NoDevice = 100,
    SetOnActiveProcess = 708,
    StartupFailure = 127,
    InvalidPtx = 218,
    UnsupportedPtxVersion = 222,
    NoKernelImageForDevice = 209,
    JitCompilerNotFound = 221,
    JitCompilationDisabled = 223,
}